Revert "feat(interpolate): improve types for nested objects"
This reverts commit 1533de7c4053d40d5238842538390dfd9c88d55a.

It resulted into the following error:
`Type instantiation is excessively deep and possibly infinite.ts(2589) error is thrown.`
which has been issued here: https://github.com/microsoft/TypeScript/issues/41406

Going to remove this until its clear what the cause is.